language: android

android:
  components:
    - platform-tools

licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+

before_install:
  - yes | sdkmanager "platforms;android-27"

env:
 global:
 - ANDROID_API=27
# - ANDROID_BUILD_TOOLS=26.0.1

script:
  - "./gradlew app:assembleDebug"


